[package]
name = "lollipop"
version = "1.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
evdev = { version = "0.13.2", features = ["tokio"] }
thiserror = "2.0.17"
tokio = { version = "1.49.0", features = ["rt-multi-thread", "macros"] }
