[package]
name = "lollipop"
version = "0.1.0"
edition = "2024"

[dependencies]
evdev = { version = "0.13.2", features = ["tokio"] }
nix = { version = "0.30.1", features = ["event", "ioctl"] }

[dependencies.tokio]
features = ["macros", "rt-multi-thread", "time"]
version = "1.17"
