[package]
name = "lollipop"
version = "1.1.1"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
evdev = { version = "0.13.2" }
nix = { version = "0.31.1", features = ["event"] }
thiserror = "2.0.17"

[profile.release]
lto = 'thin'
