[package]
name = "lollipop"
version = "1.0.0"
edition = "2024"

[dependencies]
evdev = { version = "0.13.2", features = ["tokio"] }

[dependencies.tokio]
features = ["macros", "rt-multi-thread", "time"]
version = "1.17"
